---
title: "USA fatalities due to tornados and high winds from 1950 to 2011"
author: "By padames"
date: "March 19, 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE}
library(leaflet)
#load storm data as df
load(file="./usa_storm_data.RData")
#Testing that there is actually data to work with:
#df[df$EVT_TYPE == "Hurricanes/Tornados/Thunderstorms" & df$FATALITIES > 100,][c('STATE','LATITUDE','LONGITUDE')]

GetStateStormData <- function( stormDataFrame, EffectName, EventType, cutOffLabels=1.0) {
    ## stormDataFrame, ST=state abbreviation, EffectName=exact data frame column heading
    ## Subset the storm.data.frame
    #storm_data_ST <- stormDataFrame[stormDataFrame$STATE == ST,]
    storm_data_ST_EvtType <- stormDataFrame[ stormDataFrame$EVT_TYPE == EventType
                                            & stormDataFrame[EffectName]>=1,]
    
    maxVal<-max(storm_data_ST_EvtType[EffectName]) # extract the value 
    scaling_factor<- cutOffLabels * maxVal/6.0
    cex_values <- sapply( X=as.vector(storm_data_ST_EvtType[EffectName]),
                          FUN=function(x) x/scaling_factor ) 

#    points(-storm_data_ST_EvtType$LONGITUDE/100, storm_data_ST_EvtType$LATITUDE/100, 
#           pch=21, bg=alpha("red",0.25), cex=cex_values)
    
    ST_EvtType <- storm_data_ST_EvtType[ storm_data_ST_EvtType[EffectName] >= scaling_factor, ]
    years <- as.character(format( as.Date(ST_EvtType$BGN_DATE, format = "%m/%d/%Y %H:%M:%S"), "%Y"))
    effectCount <- as.character(ST_EvtType[EffectName][,1]) 
    yearEffectCount <- paste0(years,rep(x=" (",length(years)), effectCount,rep(x=")",length(years)))
    maxLabel <- max(as.numeric(effectCount))
    scaling_factor_label <- maxLabel/1.5
    cex_labels <- sapply( X=as.vector(effectCount),FUN=function(x) as.numeric(x)/scaling_factor_label ) 
    pos_labels <- rep(c(2,1,1,4),times=(length(cex_labels)/4))
#    text( -ST_EvtType$LONGITUDE/100, cex=cex_labels, ST_EvtType$LATITUDE/100, labels=yearEffectCount, pos=pos_labels )
    
    df <- storm_data_ST_EvtType[storm_data_ST_EvtType$LATITUDE > 0 & storm_data_ST_EvtType$LONGITUDE > 0,]
    dfMod <- transform( df, LATITUDE=df$LATITUDE/100, LONGITUDE=-df$LONGITUDE/100)
}

GenerateFatalityLabels <- function(df){
  yearsTornados <-as.character(strftime(as.Date.factor(df$BGN_DATE,format= "%d/%m/%Y"),"%Y-%m-%d"))
  labels <- mapply(FUN=function(x,y,z) paste(sep=" ", 
                                   ifelse(is.na(y), "No date: ", paste0(y, ": ")), 
                                   paste0(z, " ", as.character(x),
                                          ifelse(x<2," fatality"," fatalities"))),
         df$FATALITIES, 
         yearsTornados, 
         df$EVTYPE )
  l <- unlist(labels)
  
}


dfFatalities <- GetStateStormData(df,"FATALITIES","Hurricanes/Tornados/Thunderstorms")

#paste0("ALL = ",length(df$COUNTY))
#paste0("AL = ", length(dfST$COUNTY))
#paste0("Ratio = ", length(dfST$COUNTY)/length(df$COUNTY) )


#df %>% 
#popup_labels <- sapply( X=dfFatalities$FATALITIES,FUN=function(x) paste0( as.character(x), " fatalities") )
years <-as.character(strftime(as.Date.factor(dfFatalities$BGN_DATE,format= "%d/%m/%Y"),"%Y-%m-%d"))
popup_labels <- mapply(FUN=function(x,y,z) paste(sep=" ", 
                                                 ifelse(is.na(y), "No date: ", paste0(y, ": ")), 
                                                 paste0(z, " ", as.character(x),
                                                        ifelse(x<2," fatality"," fatalities"))),
                       dfFatalities$FATALITIES, 
                       years, 
                       dfFatalities$EVTYPE)

dfFatalities$Label <- popup_labels

dfFatalTornados <- dfFatalities[dfFatalities$EVTYPE=="TORNADO",]
dfFatalHighWind <- dfFatalities[dfFatalities$EVTYPE=="HIGH WIND",]
dfFatalThunderWind <- dfFatalities[dfFatalities$EVTYPE=="THUNDERSTORM WIND",]
dfFatalMarineWind <- dfFatalities[(dfFatalities$EVTYPE=="MARINE STRONG WIND") | (dfFatalities$EVTYPE == "MARINE THUNDERSTORM WIND"),]

dfFatalTornados$Label <- GenerateFatalityLabels(dfFatalTornados)
dfFatalHighWind$Label <- GenerateFatalityLabels(dfFatalHighWind)
dfFatalThunderWind$Label <- GenerateFatalityLabels(dfFatalThunderWind)
dfFatalMarineWind$Label <- GenerateFatalityLabels(dfFatalMarineWind)

leaflet() %>% 
  addTiles() %>% 
  addMarkers(data= dfFatalTornados,
             lat = ~ LATITUDE, 
             lng = ~ LONGITUDE, 
             label = ~ Label,
             labelOptions = labelOptions(noHide = F, textsize = "12px"),
             clusterOptions = markerClusterOptions(),
             group = "Tornados") %>%
  addMarkers(data= dfFatalHighWind,
             lat = ~ LATITUDE, 
             lng = ~ LONGITUDE, 
             label = ~ Label,
             labelOptions = labelOptions(noHide = F, textsize = "12px"),
             clusterOptions = markerClusterOptions(),
             group = "High Winds") %>%
  addMarkers(data= dfFatalThunderWind,
             lat = ~ LATITUDE, 
             lng = ~ LONGITUDE, 
             label = ~ Label,
             labelOptions = labelOptions(noHide = F, textsize = "12px"),
             clusterOptions = markerClusterOptions(),
             group = "Thunderstorms") %>%
  addMarkers(data= dfFatalMarineWind,
             lat = ~ LATITUDE, 
             lng = ~ LONGITUDE, 
             label = ~ Label,
             labelOptions = labelOptions(noHide = F, textsize = "12px"),
             clusterOptions = markerClusterOptions(),
             group = "Marine Winds") %>%  
  addLayersControl(
    overlayGroups=c("Tornados","High Winds","Thunderstorms","Marine winds"),
    options=layersControlOptions(collapsed=FALSE))
```

The storm data was collected by Dr. Roger Peng from a public data base of the U.S. National Oceanic and Atmospheric Administration (NOAA) and provided to students of the Reproducible Reserach Course. It was downloaded in November, 2014 from
[compressed file](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2). 
Additional code was added to filter the fatality data for the Tornado and high wind storm events.

